### PR TITLE
Patch notebook < 7 dependencies for jupyter_client and pyzmq

### PR DESCRIPTION
**Pull request by RRosio**
Checklist
* [x] Ran `python show_diff.py` and posted the output as part of the PR.
* [x] Modifications won't affect packages built in the future. 

Having trouble running this script due to issues with conda/conda_build. After installing the conda_build with `pip` it pulled [2.1.5](https://pypi.org/project/conda-build/) and the following is the error message I am running into:
```
(repodata_notebook_cf) ➜ rosio@Rosios-MacBook-Pro  ~/Desktop/code/conda-forge/conda-forge-repodata-patches-feedstock/recipe git:(notebook_patch) python show_diff.py    
Traceback (most recent call last):
  File "/Users/me/Desktop/code/conda-forge/conda-forge-repodata-patches-feedstock/recipe/show_diff.py", line 12, in <module>
    from conda_build.index import _apply_instructions
  File "/Users/me/osx64/miniconda3/lib/python3.9/site-packages/conda_build/index.py", line 14, in <module>
    from conda_build.utils import file_info, get_lock, try_acquire_locks
  File "/Users/me/osx64/miniconda3/lib/python3.9/site-packages/conda_build/utils.py", line 27, in <module>
    from .conda_interface import md5_file, unix_path_to_win, win_path_to_unix
  File "/Users/me/osx64/miniconda3/lib/python3.9/site-packages/conda_build/conda_interface.py", line 9, in <module>
    from conda import compat, plan  # NOQA
ImportError: cannot import name 'compat' from 'conda' (/Users/me/osx64/miniconda3/lib/python3.9/site-packages/conda/__init__.py)
```

### CODE REVIEW

File: recipe/gen_patch_json.py [hunk 1]
```diff
@@ -1706,6 +1706,26 @@ def _gen_new_index_per_key(repodata, subdir, index_key):
                 i = record["depends"].index("pyyaml")
                 record["depends"][i] = "pyyaml >=6.0"
 
+        # Notebook 6.5.5 pins the versions of jupyter_client to < 8
+        # and pyzmq>=25 as a temporary fix for issue
+        # https://github.com/jupyter/notebook/issues/4439
+        # all versions of Notebook < 7 should at least pin to 
+        # jupyter_client < 8 and pyzmq < 25 as in
+        # https://github.com/jupyter/notebook/pull/6749
+        if record_name == "notebook" and int(record["version"].split(".", 1)[0]) < 7:
```
Comment (bollwyvl) [inline recipe/gen_patch_json.py:1715]: Note the second checklist item in the PR template...

> Make sure to add a condition `and record.get("timestamp", 0) < NOW` so your changes only affect packages built in the past. Replace NOW with `python -c "import time; print(f'{time.time():.0f}000')"` -->

...so perhaps something like:

```py
if (
    record_name == "notebook" 
    and int(record["version"].split(".", 1)[0]) < 7
    and record.get("timestamp", 0) < 1691035398000
):
```

**Comment by bollwyvl** [comment]
you can get the diff output from a known-good env on CI, a la:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=755339&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=387

(view raw log, snip out the relevant bits)

> After installing the `conda_build` with `pip`

Yeah, whatever it says on the tin, pretty much nothing from `conda` up is going to work when installed with pip.

For conda-forge related stuff, i recommend:
- start with a dedicated [miniforge](https://conda-forge.org/miniforge) install
 - ideally `mambaforge`, as that's what
- create an environment with "the conda-forge junk"

```yaml
# environment.yml
channels:
- conda-forge
- nodefaults
dependencies:
- python >=3.11,<3.12
- mamba
- boa
- conda-smithy
- conda-build
- conda-lock
- grayskull
- conda-suggest
```

do all conda-forge-related stuff from this env, and keep it relatively up-to-date.

**Comment by hmaarrfk** [comment]
I'm wondering if 1 year later this is still desired or if we can close it? thanks!
